import { Hero } from './hero';

export const HEROES: Hero[] = [
    {name: "Blue_Jazz", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Blue_Jazz.png", id: 1, party: false},
    {name: "Cauliflower", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Cauliflower.png", id: 2, party: false},
    {name: "Coffee_Bean", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Coffee_Bean.png", id: 3, party: false},
    {name: "Garlic", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Garlic.png", id: 4, party: false},
    {name: "Green_Bean", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Green_Bean.png", id: 31, party: false},
    {name: "Kale", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Kale.png", id: 31, party: false},
    {name: "Parsnip", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Parsnip.png", id: 31, party: false},
    {name: "Potato", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Potato.png", id: 31, party: false},
    {name: "Rhubarb", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Rhubarb.png", id: 31, party: false},
    {name: "Strawberry", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Strawberry.png", id: 31, party: false},
    {name: "Tulip", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Tulip.png", id: 31, party: false},
    {name: "Blueberry", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Blueberry.png", id: 31, party: false},
    {name: "Corn", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Corn.png", id: 31, party: false},
    {name: "Hops", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Hops.png", id: 31, party: false},
    {name: "Hot_Pepper", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Hot_Pepper.png", id: 31, party: false},
    {name: "Melon", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Melon.png", id: 31, party: false},
    {name: "Poppy", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Poppy.png", id: 31, party: false},
    {name: "Radish", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Radish.png", id: 31, party: false},
    {name: "Red_Cabbage", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Red_Cabbage.png", id: 31, party: false},
    {name: "Starfruit", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Starfruit.png", id: 31, party: false},
    {name: "Summer_Spangle", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Summer_Spangle.png", id: 31, party: false},
    {name: "Sunflower", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Sunflower.png", id: 31, party: false},
    {name: "Tomato", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Tomato.png", id: 31, party: false},
    {name: "Wheat", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Wheat.png", id: 31, party: false},
    {name: "Amaranth", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Amaranth.png", id: 31, party: false},
    {name: "Artichoke", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Artichoke.png", id: 31, party: false},
    {name: "Beet", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Beet.png", id: 31, party: false},
    {name: "Bok_Choy", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Bok_Choy.png", id: 31, party: false},
    {name: "Cranberries", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Cranberries.png", id: 31, party: false},
    {name: "Eggplant", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Eggplant.png", id: 31, party: false},
    {name: "Fairy_Rose", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Fairy_Rose.png", id: 31, party: false},
    {name: "Grape", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Grape.png", id: 31, party: false},
    {name: "Pumpkin", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Pumpkin.png", id: 31, party: false},
    {name: "Yam", property: "Paper", type: "Balance", terr1: "Grass", imgurl: "../assets/Yam.png", id: 31, party: false}
];
